## Setup

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import math
import torch
import matplotlib.pyplot as plt
from pathlib import Path
from torch import tensor

### Generate Two Random Matrices (A and B)

In [3]:
A = torch.randint(0,10, (3,2))
B = torch.randint(0,10, (2,3))
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

Matrix A:
 tensor([[7, 5],
        [0, 1],
        [7, 4]])

Matrix B:
 tensor([[4, 7, 0],
        [4, 8, 6]])


## Matrix Multiplication

### Challenge #1: Write a function to multiply two matrices together
I strongly recommend using http://matrixmultiplication.xyz/ and following along step-by-step with pen and paper if you're not super comfortable with matrix multiplication. Generate a few random matrices and make sure you can multipy them by hand without help before trying to write the code. Also, don't forget "row by column, row by column..."

In [4]:
# View Matrices:
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

Matrix A:
 tensor([[7, 5],
        [0, 1],
        [7, 4]])

Matrix B:
 tensor([[4, 7, 0],
        [4, 8, 6]])


In [5]:
def matrix_multiply(A, B):
    # Assert that matrices are compatible
    
    # Create new matrix based on resulting output shape

    # Matrix multiplication:

    # Return new matrix

In [6]:
print(matrix_multiply(A, B))

tensor([[48., 89., 30.],
        [ 4.,  8.,  6.],
        [44., 81., 24.]])


In [7]:
# Verify that our code is correct:
A @ B

tensor([[48, 89, 30],
        [ 4,  8,  6],
        [44, 81, 24]])

In [8]:
# Test performance:
%timeit matrix_multiply(A,B)

337 µs ± 6.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Challenge #2: Try to Predict Output of Broadcasting Examples
<i>Before running the cells!</i>

#### Broadcasting Example #1:

In [9]:
a = torch.randint(0,10, (1,4)); a

tensor([[4, 9, 7, 5]])

In [10]:
b = torch.tensor([3])

Broadcast Code:
```python
a * b
```

My Prediction:
```python
[???]
```

In [18]:
# Actual Output: (uncomment cell below)
# a * b

#### Broadcasting Example #2:

In [12]:
a = torch.randint(0, 5, (3,3)); a

tensor([[3, 0, 4],
        [2, 3, 4],
        [4, 3, 3]])

In [13]:
b = torch.tensor([5, 2, 1]); b

tensor([5, 2, 1])

Broadcast Code:
```python
a * b
```

My Prediction:
```python
???
```

In [14]:
# Actual Output: (uncomment cell below)
a * b

tensor([[15,  0,  4],
        [10,  6,  4],
        [20,  6,  3]])

#### Broadcasting Example #3:

In [15]:
a = torch.randint(0, 5, (3,3)); a

tensor([[2, 2, 3],
        [2, 1, 0],
        [3, 4, 2]])

In [16]:
b = torch.tensor([3,4,5,1]); b

tensor([3, 4, 5, 1])

Broadcast Code:
```python
a * b
```

My Prediction:
```python
???
```

In [1]:
# Actual Output: (uncomment cell below)
# a * b

#### Broadcasting Example #4:

In [ ]:
a = torch.randint(0, 5, (1,3)); a

Broadcast Code:
```python
a[None:,]
```

My Prediction:
```python
???
```

In [ ]:
# Actual Output: (uncomment cell below)
a[None:,]

#### Broadcasting Example #5:

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]]); a

In [ ]:
b = torch.randint(0, 5, (3,3)); b

Broadcast Code:
```python
a[-1:,].expand_as(b)
```

My Prediction:
```python
???
```

In [ ]:
# Actual Output: (uncomment cell below)
a[-1:,].expand_as(b)

#### Broadcasting Example #6:

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6], [7,8,9]]); a

In [ ]:
b = torch.tensor([0, 10, 20]); b

Broadcast Code:
```python
print(a.shape[1])
print(a.unsqueeze(0).shape)
print(b.unsqueeze(1).shape)
```

My Prediction:
```python
???
```

In [ ]:
# Actual Output: (uncomment cell below)
print(a.shape[1])
print(a.unsqueeze(0).shape)
print(b.unsqueeze(1).shape)

### Challege #3: Refactor matrix multiplication function to use broadcasting

In [ ]:
# View Matrices:
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

In [19]:
def matrix_multiply(A, B):
    pass

In [ ]:
# Verify that our code is correct:
A @ B

In [ ]:
print(matrix_multiply(A, B))

In [ ]:
# Test performance:
%timeit matrix_multiply(A,B)

##### Convince Yourself This Works:

In [ ]:
A[0][:,None]

In [ ]:
B

In [ ]:
A[0][:,None] * B

In [ ]:
(A[0][:,None] * B).sum()

In [ ]:
(A[0][:,None] * B).sum(dim=1)

In [ ]:
(A[0][:,None] * B).sum(dim=0)

### Challenge #4: Write a matrix transpose function using einstein summation notation

In [ ]:
A = torch.randint(0,5, (3,4)); A

In [ ]:
def transpose(matrix):
    pass

In [ ]:
transpose(A)

In [ ]:
A.t()

### Challenge #5: Rewrite matrix multiplication to use einstein summation

In [ ]:
A = torch.randint(0,10, (3,3))
B = torch.randint(0,10, (3,3))
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

In [ ]:
def matrix_multiply(A, B):
    pass

In [ ]:
# Verify that our code is correct:
A @ B

In [ ]:
print(matrix_multiply(A, B))

In [ ]:
# Test performance:
%timeit matrix_multiply(A,B)

In [ ]:
# Test Speed without assert and new matrix:

In [ ]:
def matrix_multiply(A, B):
    pass

In [ ]:
# Test performance:
%timeit matrix_multiply(A,B)