## Setup

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import math
import torch
import matplotlib.pyplot as plt
from pathlib import Path
from torch import tensor

### Generate Two Random Matrices (A and B)

In [3]:
A = torch.randint(0,10, (3,2))
B = torch.randint(0,10, (2,3))
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

Matrix A:
 tensor([[7, 5],
        [0, 1],
        [7, 4]])

Matrix B:
 tensor([[4, 7, 0],
        [4, 8, 6]])


## Matrix Multiplication

### Challenge #1: Write a function to multiply two matrices together

In [4]:
# View Matrices:
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

Matrix A:
 tensor([[7, 5],
        [0, 1],
        [7, 4]])

Matrix B:
 tensor([[4, 7, 0],
        [4, 8, 6]])


In [5]:
def matrix_multiply(A, B):
    # Assert that matrices are compatible
    assert(A.shape[0] == B.shape[1])
    
    # Create new matrix based on resulting output shape
    new_matrix = torch.empty(A.shape[0], B.shape[1])
    
    # Matrix Multiplication:
    for row_index_A in range(A.shape[0]):
        for column_index_B in range(B.shape[1]):
            new_matrix[row_index_A, column_index_B] = sum(A[row_index_A,:] * B[:,column_index_B])
            
    return(new_matrix)

In [6]:
print(matrix_multiply(A, B))

tensor([[48., 89., 30.],
        [ 4.,  8.,  6.],
        [44., 81., 24.]])


In [7]:
# Verify that our code is correct:
A @ B

tensor([[48, 89, 30],
        [ 4,  8,  6],
        [44, 81, 24]])

In [8]:
# Test performance:
%timeit matrix_multiply(A,B)

337 µs ± 6.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Challenge #2: Try to Predict Output of Broadcasting Examples
<i>Before running the cells!</i>

#### Broadcasting Example #1:

In [9]:
a = torch.randint(0,10, (1,4)); a

tensor([[4, 9, 7, 5]])

In [10]:
b = torch.tensor([3])

Broadcast Code:
```python
a * b
```

My Prediction:
```python
[6, 6, 27, 6]
```

In [11]:
# Actual Output: (uncomment cell below)
a * b

tensor([[12, 27, 21, 15]])

#### Broadcasting Example #2:

In [12]:
a = torch.randint(0, 5, (3,3)); a

tensor([[3, 0, 4],
        [2, 3, 4],
        [4, 3, 3]])

In [13]:
b = torch.tensor([5, 2, 1]); b

tensor([5, 2, 1])

Broadcast Code:
```python
a * b
```

My Prediction:
```python
[[20, 0, 2],
 [10, 6, 0],
 [15, 6, 4]]
```

In [14]:
# Actual Output: (uncomment cell below)
a * b

tensor([[15,  0,  4],
        [10,  6,  4],
        [20,  6,  3]])

#### Broadcasting Example #3:

In [15]:
a = torch.randint(0, 5, (3,3)); a

tensor([[2, 2, 3],
        [2, 1, 0],
        [3, 4, 2]])

In [16]:
b = torch.tensor([3,4,5,1]); b

tensor([3, 4, 5, 1])

Broadcast Code:
```python
a * b
```

My Prediction:
```python
None
```

In [17]:
# Actual Output: (uncomment cell below)
a * b

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

#### Broadcasting Example #4:

In [ ]:
a = torch.randint(0, 5, (1,3)); a

Broadcast Code:
```python
a[None:,]
```

My Prediction:
```python
tensor([[1,4,0]])
```

In [ ]:
# Actual Output: (uncomment cell below)
a[None:,]

#### Broadcasting Example #5:

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6]]); a

In [ ]:
b = torch.randint(0, 5, (3,3)); b

Broadcast Code:
```python
a[-1:,].expand_as(b)
```

My Prediction:
```python
tensor([[4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]])
```

In [ ]:
# Actual Output: (uncomment cell below)
a[-1:,].expand_as(b)

#### Broadcasting Example #6:

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6], [7,8,9]]); a

In [ ]:
b = torch.tensor([0, 10, 20]); b

Broadcast Code:
```python
print(a.shape[1])
print(a.unsqueeze(0).shape)
print(b.unsqueeze(1).shape)
```

My Prediction:
```python
3
[1,3,3]
[3,1]
```

In [ ]:
# Actual Output: (uncomment cell below)
print(a.shape[1])
print(a.unsqueeze(0).shape)
print(b.unsqueeze(1).shape)

### Challege #3: Refactor matrix multiplication function to use broadcasting

In [ ]:
# View Matrices:
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

In [ ]:
def matrix_multiply(A, B):
    # Assert that matrices are compatible
    assert(A.shape[0] == B.shape[1])
    
    # Create new matrix based on resulting output shape
    new_matrix = torch.empty(A.shape[0], B.shape[1])
    
    # Matrix Multiplication:
    for row_index in range(A.shape[0]):
        new_matrix[row_index] = torch.sum(A[row_index][:,None] * B, dim=0)
            
    return(new_matrix)

In [ ]:
# Verify that our code is correct:
A @ B

In [ ]:
print(matrix_multiply(A, B))

In [ ]:
# Test performance:
%timeit matrix_multiply(A,B)

##### Convince Yourself This Works:

In [ ]:
A[0][:,None]

In [ ]:
B

In [ ]:
A[0][:,None] * B

In [ ]:
(A[0][:,None] * B).sum()

In [ ]:
(A[0][:,None] * B).sum(dim=1)

In [ ]:
(A[0][:,None] * B).sum(dim=0)

### Challenge #4: Write a matrix transpose function using einstein summation notation

In [ ]:
A = torch.randint(0,5, (3,4)); A

In [ ]:
def transpose(matrix):
    return torch.einsum('ik->ki', matrix)

In [ ]:
transpose(A)

In [ ]:
A.t()

### Challenge #5: Rewrite matrix multiplication to use einstein summation

In [ ]:
A = torch.randint(0,10, (3,3))
B = torch.randint(0,10, (3,3))
print("Matrix A:\n", A); print(); print("Matrix B:\n", B)

In [ ]:
def matrix_multiply(A, B):
    # Assert that matrices are compatible
    assert(A.shape[0] == B.shape[1])
    
    # Create new matrix based on resulting output shape
    new_matrix = torch.empty(A.shape[0], B.shape[1])
    
    # Matrix Multiplication:
    new_matrix = torch.einsum('ab,cd->ad', A, B)

    return(new_matrix)

In [ ]:
# Verify that our code is correct:
A @ B

In [ ]:
print(matrix_multiply(A, B))

In [ ]:
# Test performance:
%timeit matrix_multiply(A,B)

In [ ]:
# Test Speed without assert and new matrix:

In [ ]:
def matrix_multiply(A, B):
    return torch.einsum('ab,cd->ad', A, B)

In [ ]:
# Test performance:
%timeit matrix_multiply(A,B)